# Generated by Django 4.0.3 on 2022-04-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='Tutorial', max_length=50),
            preserve_default=False,
        ),
    ]
