# Generated by Django 4.0.3 on 2022-04-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
