# Generated by Django 4.0.3 on 2022-04-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_event_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
