# Generated by Django 4.0.3 on 2022-04-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_event_duration_in_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
